# Cannot pull from IB in dev due to removing H2 
FROM quay.io/keycloak/keycloak:12.0.4 AS keycloak

# Add the plugin config files
COPY development/baby-yoda.json /opt/baby-yoda.json
COPY development/baby-yoda.yaml /opt/baby-yoda.yaml

# Iinclude JS Console in dev
COPY development/js-console.war /opt/jboss/keycloak/standalone/deployments/js-console.war

# Include the mTLS certs
COPY development/certs /etc/x509/https  

# Disable theme caching
COPY development/disable-theme-cache.cli /opt/jboss/startup-scripts/disable-theme-cache.cli

# Add keycloak initializer
COPY chart/scripts/bigbang.cli /opt/jboss/startup-scripts/keycloak-init.cli

COPY development/x509.sh /opt/jboss/tools/x509.sh

# ENV KEYCLOAK_IMPORT /opt/baby-yoda.json
ENV DB_VENDOR h2
ENV KEYCLOAK_USER admin 
ENV KEYCLOAK_PASSWORD pass
ENV JAVA_OPTIONS "-Dkeycloak.profile=preview -Dkeycloak.profile.feature.admin_fine_grained_authz=enabled"
ENV JAVA_TOOL_OPTIONS "-agentlib:jdwp=transport=dt_socket,address=*:5005,server=y,suspend=n"
ENV KEYCLOAK_LOGLEVEL DEBUG
ENV WILDFLY_LOGLEVEL DEBUG
ENV CUSTOM_REGISTRATION_CONFIG /opt/baby-yoda.yaml
ENV X509_CA_BUNDLE /etc/x509/https/dod_cas.pem

USER root

RUN chown -R jboss /etc/x509/https && \
    chmod 400 /etc/x509/https/*

USER jboss