ARG PLUGIN_VERSION=1.0.7
ARG KEYCLOAK_VERSION=14.0.0
# This is the bigbang configuration version
# can be reset back to 1 if either the plugin or keycloak version changes
ARG BIGBANG_VERSION=1

ARG PLUGIN_JAR=platform-one-sso-$PLUGIN_VERSION-all.jar

build-plugin:
    FROM registry1.dso.mil/ironbank/opensource/gradle/gradle-jdk8

    COPY plugin .
    RUN gradle build --info -P version=$PLUGIN_VERSION

    SAVE ARTIFACT build/libs/$PLUGIN_JAR

build-jar:
    FROM +build-plugin
    SAVE ARTIFACT build/libs/$PLUGIN_JAR AS LOCAL plugin/build/docker/p1.jar

build-image:
    FROM registry1.dso.mil/ironbank/opensource/keycloak/keycloak:$KEYCLOAK_VERSION

    COPY +build-plugin/* /opt/jboss/keycloak/standalone/deployments/
    COPY x509.sh /opt/jboss/tools/x509.sh
    COPY bigbang.cli /opt/jboss/startup-scripts/keycloak-init.cli

    # Temporary reminder to update the chart until we decide the cleanest way to automate this
    RUN echo -e "\n\n\n\033[1;93m  ✅ BE SURE TO UPDATE THE \"../chart/values.yaml\" WITH THE UPDATED IMAGE TAG: \"$KEYCLOAK_VERSION-$PLUGIN_VERSION-$BIGBANG_VERSION\"\n\n\n"

    SAVE IMAGE registry.dso.mil/platform-one/big-bang/apps/security-tools/keycloak/keycloak-ib:$KEYCLOAK_VERSION-$PLUGIN_VERSION-$BIGBANG_VERSION

build-dev-image:
    # Cannot pull from IB in dev due to removing H2
    FROM quay.io/keycloak/keycloak:$KEYCLOAK_VERSION

    # Add the plugin config files
    COPY baby-yoda.* /opt/

    # Iinclude JS Console in dev
    COPY js-console.war /opt/jboss/keycloak/standalone/deployments/js-console.war

    # Include the mTLS certs
    COPY certs /etc/x509/https

    # Disable theme caching
    COPY disable-theme-cache.cli /opt/jboss/startup-scripts/disable-theme-cache.cli

    # Add required scripts to boot sequence
    COPY x509.sh /opt/jboss/tools/x509.sh
    COPY bigbang.cli /opt/jboss/startup-scripts/keycloak-init.cli

    ENV KEYCLOAK_IMPORT /opt/baby-yoda.json
    ENV DB_VENDOR h2
    ENV KEYCLOAK_USER admin
    ENV KEYCLOAK_PASSWORD pass
    ENV JAVA_OPTS_APPEND "-Dkeycloak.profile=preview -Dkeycloak.profile.feature.admin_fine_grained_authz=enabled"
    ENV JAVA_TOOL_OPTIONS "-agentlib:jdwp=transport=dt_socket,address=*:5005,server=y,suspend=n"
    ENV CUSTOM_REGISTRATION_CONFIG /opt/baby-yoda.yaml
    ENV X509_CA_BUNDLE /etc/x509/https/dod_cas.pem

    USER root

    RUN chown -R jboss /etc/x509/https && \
        chmod 400 /etc/x509/https/*

    USER jboss

    SAVE IMAGE p1-sso-dev:latest

run-dev:
    LOCALLY

    RUN rm -fr plugin/build

    RUN earthly +build-jar
    RUN earthly +build-dev-image

    RUN docker run -p 8443:8443 -p 5005:5005 \
        -v $PWD/plugin/build/docker:/opt/jboss/keycloak/standalone/deployments \
        -v $PWD/plugin/src/main/resources/theme/p1-sso:/opt/jboss/keycloak/themes/p1-sso-live-dev \
        p1-sso-dev:latest
