apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
imagePullSecrets:
  - name: private-registry
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keycloak
imagePullSecrets:
  - name: private-registry
