apiVersion: v1
kind: Service
metadata:
  name: keycloak-headless
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/instance: "keycloak"
    app.kubernetes.io/version: "10.0.1"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: https
      port: 8443
      targetPort: https
      protocol: TCP
    - name: jgroups
      port: 7600
      targetPort: jgroups
      protocol: TCP
  selector:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/instance: "keycloak"
