apiVersion: v1
kind: Service
metadata:
  name: keycloak-http
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/instance: "keycloak"
    app.kubernetes.io/version: "10.0.0"
spec:
  type: ClusterIP
  ports:
    - name: https
      port: 8443
      targetPort: https
      protocol: TCP
  selector:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/instance: "keycloak"