{{- /* the allow-nothing policy should eventually be provided by istio itself cluster-wide */ -}}
{{- if and .Values.istio.enabled .Values.istio.hardened.enabled -}}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-nothing-policy
  namespace: {{ .Release.Namespace }}
spec: {}
{{- end }}

