namespace: keycloak

resources:
  - namespace.yaml
  - generate/generated.yaml

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: keycloak
      namespace: keycloak
    path: patches/statefulset-jgroups.yaml
  - target:
      version: v1
      kind: Service
      name: keycloak-headless
      namespace: keycloak
    path: patches/service-jgroups.yaml
