{{- if .Values.scripts }}
{{- $highAvailability := gt (int .Values.replicas) 1 -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak.fullname" . }}-sh
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
  namespace: {{ $.Release.Namespace }}
data:
  {{- range $key, $value := .Values.scripts }}
  {{ $key }}: |
    {{- tpl $value $ | nindent 4 }}
  {{- end }}
{{- end -}}
