{{- if .Values.virtualService.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
  namespace: {{ $.Release.Namespace }}
spec:
  # Override both hosts entries as needed, note the tls: match should be completely replaced in overlays since its an array
  hosts:
    {{- toYaml .Values.virtualService.hosts | nindent 4 }}
  gateways:
    {{- toYaml .Values.virtualService.gateways | nindent 4 }}
  http:
    - route:
      - destination:
          host: {{ include "keycloak.fullname" . }}-http
  tls:
    - match:
      - port: {{ .Values.virtualService.port }}
        sniHosts:
          {{- toYaml .Values.virtualService.sniHosts | nindent 12 }}
      route:
      - destination:
          host: {{ include "keycloak.fullname" . }}-http
          port:
            number: {{ .Values.service.httpsPort }}
{{- end }}
