{{ if .Values.istio.enabled }}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: keycloak-postgresql-exception
  namespace: {{ .Release.Namespace }}
spec:
  mtls:
    mode: {{ .Values.istio.mtls.mode }}
  selector:
    matchLabels:
      app.kubernetes.io/name: postgresql
  portLevelMtls:
    "5432":
      mode: PERMISSIVE
{{- end }}
