namespace: keycloak

resources:
  - namespace.yaml
  - generate/generated.yaml

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: keycloak
      namespace: keycloak
    path: patches/statefulset-jgroups.yaml
  - target:
      version: v1
      kind: Service
      name: keycloak-headless
      namespace: keycloak
    path: patches/service-jgroups.yaml

images:
  # Use our own custom image
  # NOTE: It is up to the "consumer" to provide the necssary ImagePullSecrets to pull this
  - name: jboss/keycloak:9.0.2
    newName: registry.dsop.io/platform-one/private/big-bang/apps/keycloak
    # TODO: Make this a real tag!
    newTag: master
