apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
spec:
  podSelector: {}
  policyTypes:
    - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: inbound-https
spec:
  policyTypes:
    - Ingress
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ template "keycloak.fullname" . }}
  ingress:
    - ports:
        - protocol: TCP
          port: {{ .Values.service.httpsPort }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: inbound-jgroups
spec:
  policyTypes:
    - Ingress
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ template "keycloak.fullname" . }}
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: {{ template "keycloak.fullname" . }}
      ports:
        - protocol: TCP
          port: 7600
---
{{- if .Values.postgresql.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: inbound-database-dev
spec:
  policyTypes:
    - Ingress
  podSelector:
    matchLabels:
      app.kubernetes.io/name: postgresql
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: {{ template "keycloak.fullname" . }}
    - ports:
        - protocol: TCP
          port: 5432
{{- end }}
---
{{- if .Values.monitoring.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: inbound-prometheus
spec:
  policyTypes:
    - Ingress
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ template "keycloak.fullname" . }}
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            app.kubernetes.io/name: monitoring
        podSelector:
          matchLabels:
            app: prometheus
    - ports:
        - protocol: TCP
          port: {{ .Values.service.httpManagementPort }}
{{- end }}