{{- if and .Values.istio.enabled .Values.istio.keycloak.enabled -}}
{{- $serviceName := printf "%s-http" (include "keycloak.fullname" .) -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ template "keycloak.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ include "keycloak.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: keycloak
spec:
  gateways:
  {{- range .Values.istio.keycloak.gateways }}
    - {{ . }}
  {{- end }}
  hosts:
  {{- range .Values.istio.keycloak.hosts }}
    - {{ tpl . $}}
  {{- end }}
  http:
    - route:
      - destination:
          port:
            number: {{ .Values.service.httpPort }}
          host: {{ $serviceName }}
  tls:
  - match:
    - port: 8443
      sniHosts:
      {{- range .Values.istio.keycloak.hosts }}
      - {{ tpl . $}}
      {{- end }}
    route:
    - destination:
        host: {{ $serviceName }}
        port:
          number: {{ .Values.service.httpsPort }}
{{- end }}