{{- /* Render Istio ServiceEntries */ -}}
{{- if and .Values.istio.enabled .Values.istio.hardened.enabled -}}
{{- range .Values.istio.hardened.customServiceEntries -}}
{{- if .enabled -}}
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  {{- toYaml .spec | nindent 2 }}
---
{{ end -}}
{{ end -}}
{{- end -}}