apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/instance: "keycloak"
    app.kubernetes.io/version: "10.0.1"

spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: keycloak
      app.kubernetes.io/instance: "keycloak"
  replicas: 2
  serviceName: keycloak-headless
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: keycloak
        app.kubernetes.io/instance: "keycloak"
    spec:
      restartPolicy: Always
      serviceAccountName: keycloak
      securityContext:
        fsGroup: 1000
      containers:
        - name: keycloak
          image: "keycloak-placeholder"
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
          command:
            - /scripts/keycloak.sh
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=50.0"

            - name: PROXY_ADDRESS_FORWARDING
              value: "true"

            - name: JGROUPS_DISCOVERY_PROTOCOL
              value: dns.DNS_PING

            - name: JGROUPS_DISCOVERY_PROPERTIES
              value: dns_query=keycloak-headless.keycloak.svc.cluster.local

            - name: KEYCLOAK_SERVICE_DNS_NAME
              value: "keycloak-headless.keycloak.svc.cluster.local"

            - name: DB_VENDOR
              value: "postgres"

            - name: DB_PORT
              value: "5432"

            - name: DB_DATABASE
              value: "keycloak"

            - name: DB_ADDR
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: "PGHOST"

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: "PGUSER"

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: "PGPASSWORD"

          volumeMounts:
            - name: sh
              mountPath: /scripts
              readOnly: true
            - name: startup
              mountPath: /opt/jboss/startup-scripts
              readOnly: true
            - name: https
              mountPath: "/etc/x509/https"
              readOnly: true
          ports:
            - name: https
              containerPort: 8443
              protocol: TCP
            - name: jgroups
              containerPort: 7600
              protocol: TCP

          livenessProbe:
            httpGet:
              path: /auth/realms/master
              port: https
              scheme: HTTPS
            initialDelaySeconds: 120
            failureThreshold: 15
            periodSeconds: 15

          readinessProbe:
            httpGet:
              path: /auth/realms/master
              port: https
              scheme: HTTPS
            initialDelaySeconds: 120
            failureThreshold: 15
            timeoutSeconds: 2

      terminationGracePeriodSeconds: 60
      volumes:
        - name: sh
          configMap:
            name: keycloak-sh
            defaultMode: 0555
        - name: startup
          configMap:
            name: keycloak-startup
            defaultMode: 0555
        - name: https
          secret:
            secretName: keycloak-mtls
