{{- if and .Values.networkPolicies.enabled .Values.networkPolicies.ldap.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-ldap
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - ports:
      - port: {{ .Values.networkPolicies.ldap.port }}
        protocol: TCP
    - to:
      - ipBlock:
          cidr: {{ .Values.networkPolicies.ldap.cidr }}
{{- end}}
