{{- if .Values.networkPolicies.enabled }}
# For external smtp server
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-smtp
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - ports:
    - protocol: TCP
      port: {{ .Values.networkPolicies.smtpPort }}
    to:
    - ipBlock:
        # This should be replaced with the IP of the mail Server
        cidr: 0.0.0.0/0
        # ONLY Block requests to AWS metadata IP
        except:
          - 169.254.169.254/32
{{- end }}
