{{- if and .Values.networkPolicies.enabled .Values.istio.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-istiod
  namespace: "{{ .Release.Namespace }}"
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          {{- if .Values.networkPolicies.istioNamespaceSelector }}
          app.kubernetes.io/name: {{ .Values.networkPolicies.istioNamespaceSelector.egress }}
          {{- else }}
          app.kubernetes.io/name: "istio-controlplane"
          {{- end }}
      podSelector:
        matchLabels:
          app: istiod
    ports:
    - port: 15012
{{- end }}
