{{- if and .Values.networkPolicies.enabled (not .Values.postgresql.enabled) }}
# For external postgres server
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-postgres
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - ports:
    - protocol: TCP
      port: 5432
    to:
    - ipBlock:
        # This should be replaced with the IP of the postgresql Server
        cidr: 0.0.0.0/0
        # ONLY Block requests to AWS metadata IP
        except:
          - 169.254.169.254/32
{{- end }}