{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-dns-http-https
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
    - ports:
      - port: 53
        protocol: UDP
      - port: 80
        protocol: TCP
      - port: 443
        protocol: TCP
      {{- if .Values.openshift }}  
      - port: 5353
        protocol: UDP
      {{- end }} 
{{- end }}
