{{- if and .Values.networkPolicies.enabled .Values.postgresql.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-internal-postgres   # for development and CI pipelines
spec:
  policyTypes:
    - Ingress
  podSelector:
    matchLabels:
      app.kubernetes.io/name: postgresql
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: {{ template "keycloak.fullname" . }}
    - ports:
        - protocol: TCP
          port: 5432
{{- end }}
