{{- $monitoringEnabled := dig "serviceMonitor" "enabled" false .Values.upstream }}
{{- if and .Values.networkPolicies.enabled $monitoringEnabled }}
{{- $internalPort := (kindIs "int" .Values.keycloakx.http.internalPort) | ternary .Values.keycloakx.http.internalPort 9000 }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-monitoring
spec:
  policyTypes:
    - Ingress
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: upstream
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            app.kubernetes.io/name: monitoring
        podSelector:
          matchLabels:
            app: prometheus
    - ports:
        - protocol: TCP
          port: {{ $internalPort }}
{{- end }}
