{{- if and .Values.networkPolicies.enabled .Values.postgresql.enabled }}
{{- $postgresPort := dig "primary" "service" "ports" "postgresql" 5432 .Values.postgresql }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-internal-postgres   # for development and CI pipelines
spec:
  policyTypes:
    - Ingress
  podSelector:
    matchLabels:
      app.kubernetes.io/name: postgresql
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app.kubernetes.io/instance: {{ .Release.Name }}
            app.kubernetes.io/name: upstream
    - ports:
        - protocol: TCP
          port: {{ $postgresPort }}
{{- end }}
