{{- if and .Values.istio.enabled .Values.istio.hardened.enabled -}}
{{- $namespace := $.Release.Namespace -}}
{{- $postgresPort := dig "primary" "service" "ports" "postgresql" 5432 .Values.postgresql }}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-postgres-keycloak
  namespace: {{ $namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/instance: keycloak
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces:
        - {{ $namespace }}
  - to:
    - operation:
        ports:
        - {{ $postgresPort | quote }}
{{- end }}

