networks:
  keycloak-tier:
    driver: bridge

services:
  postgresql:
    platform: linux/amd64
    image: 'bitnami/postgresql:15.3.0'
    networks:
      - keycloak-tier
    container_name: keycloak-db
    ports:
      - '5432:5432'
    environment:
      # create database on startup, if it does not already exist
      - POSTGRESQL_USERNAME=keycloak
      - POSTGRESQL_PASSWORD=keycloak
      - POSTGRESQL_DATABASE=keycloak

  keycloak:
    platform: linux/amd64
    depends_on:
      - postgresql

    image: 'registry1.dso.mil/ironbank/opensource/keycloak/keycloak:25.0.6'

    networks:
      - keycloak-tier
    container_name: keycloak
    ports:
      # - '8080:8080'
      - '8443:8443'
    command:
      # - "start"
      - "start-dev"
      - "--import-realm"
    environment:
      # https://www.keycloak.org/server/all-config
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "password"
      KC_HTTP_RELATIVE_PATH: "/auth"
      KC_DB: "postgres"
      KC_DB_USERNAME: "keycloak"
      KC_DB_PASSWORD: "keycloak"
      KC_DB_URL_HOST: "postgresql"
      KC_DB_URL_PORT: "5432"
      KC_DB_URL_DATABASE: "keycloak"

      KC_HOSTNAME: keycloak.dev.bigbang.mil
      KC_HOSTNAME_STRICT: "true"
      KC_LOG_LEVEL: "org.keycloak.events:DEBUG,org.infinispan:INFO,org.jgroups:INFO"

      KC_HTTPS_CLIENT_AUTH: request
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/conf/tls.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/conf/tls.key
      KC_HTTPS_TRUST_STORE_FILE: /opt/keycloak/conf/truststore.jks
      KC_HTTPS_TRUST_STORE_PASSWORD: password
      
      KC_METRICS_ENABLED: "true"

      CUSTOM_REGISTRATION_CONFIG: /opt/keycloak/conf/customreg.yaml

    volumes:
    - ./certs/tls.crt:/opt/keycloak/conf/tls.crt
    - ./certs/tls.key:/opt/keycloak/conf/tls.key
    - ./certs/truststore.jks:/opt/keycloak/conf/truststore.jks
    - ./plugin/p1-keycloak-plugin-3.5.7.jar:/opt/keycloak/providers/p1-keycloak-plugin-3.5.7.jar
    - ./baby-yoda.yaml:/opt/keycloak/conf/customreg.yaml
    - ./baby-yoda.json:/opt/keycloak/data/import/realm.json
    - ./quarkus.properties:/opt/keycloak/conf/quarkus.properties
    # demonstrate 2 different ways to inject a custom theme into keycloak
    - ./theme-live-dev/theme/p1-sso-live-dev:/opt/keycloak/themes/p1-sso-live-dev
    - ./theme-custom/custom-theme.jar:/opt/keycloak/providers/custom-theme.jar
