FROM gradle:jdk11 AS build

WORKDIR /usr/src/gradle

COPY custom-registration /usr/src/gradle

RUN gradle build

FROM quay.io/keycloak/keycloak:10.0.1 AS keycloak

COPY baby-yoda.json /opt/baby-yoda.json
COPY custom-theme /opt/custom-theme
COPY --from=build /usr/src/gradle/build/libs/keycloak-registration-validation-1.2.jar /opt/jboss/keycloak/standalone/deployments/p1.jar

ENV KEYCLOAK_IMPORT /opt/baby-yoda.json
ENV DB_VENDOR h2
ENV KEYCLOAK_USER admin 
ENV KEYCLOAK_PASSWORD pass
ENV _JAVA_OPTIONS "-Xdebug -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=n -Dkeycloak.profile=preview"
ENV KEYCLOAK_LOGLEVEL DEBUG

USER root

RUN mv /opt/jboss/keycloak/themes/base /opt/jboss/keycloak/themes/base.bak && \
    mv /opt/custom-theme /opt/jboss/keycloak/themes/base && \
    mv /opt/jboss/keycloak/themes/base.bak/admin /opt/jboss/keycloak/themes/base/admin && \
    rm -fr /opt/jboss/keycloak/themes/base.bak

USER jboss